machine_type = "64k-plus-1.2-vtdos"
video_model = "interleaved"

[tape]
selected = "progs/TVBALL.CAS"
loaded = true
recent = ["progs/TVBALL.CAS"]

[disk]
selected = "progs/tvball.dsk"
loaded = true
recent = ["progs/tvball.dsk", "/Users/teki/dev/jstvc/games/kismozdony.zip", "/Users/teki/dev/jstvc/games/break.zip", "/Users/teki/dev/jstvc/games/kitoltes.zip", "/Users/teki/dev/jstvc/games/elite.zip"]
